---
- name: Setup undercloud backup facts
  set_fact:
    _log_location: "{{ tripleo_undercloud_home_dir }}/undercloud_backup.log"
    _backup_cmd: >-
      openstack undercloud backup
      {{ tripleo_undercloud_backup_add_path | shell_arg_list(parameter='--add-path') }}
      {{ tripleo_undercloud_backup_exclude_path | shell_arg_list(parameter='--exclude-path') }}
      {{ _log_location | shell_logging_path(combine=tripleo_undercloud_log_combine, enabled=tripleo_undercloud_log_output) }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ _log_location }}"

- name: Running the underclound backup command
  debug:
    var: _backup_cmd
  when: tripleo_undercloud_debug|bool

- name: undercloud backup
  shell: "{{ _backup_cmd }}"
  args:
    chdir: "{{ tripleo_undercloud_home_dir }}"
