---
- name: Setup undercloud backup facts
  set_fact:
    _backup_cmd: >-
      openstack undercloud backup
      {{ tripleo_undercloud_backup_add_path | tripleo.operator.shell_arg_list(parameter='--add-path') }}
      {{ tripleo_undercloud_backup_exclude_path | tripleo.operator.shell_arg_list(parameter='--exclude-path') }}
      {{ tripleo_undercloud_backup_log | tripleo.operator.shell_logging_path(combine=tripleo_undercloud_log_combine, enabled=tripleo_undercloud_log_output) }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_undercloud_backup_log }}"

- name: Show the underclound backup command
  debug:
    var: _backup_cmd
  when: tripleo_undercloud_debug|bool

- name: undercloud backup
  shell: "{{ _backup_cmd }}"
  args:
    chdir: "{{ tripleo_undercloud_home_dir }}"
  async: "{{ tripleo_undercloud_backup_timeout }}"
  poll: 10
