---
- name: Setup undercloud install facts
  set_fact:
    _install_cmd: >-
      openstack undercloud install
      {{ "--force-stack-update" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_install_force_stack_update) }}
      {{ "--no-validations" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_install_no_validations) }}
      {{ "--inflight-validations" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_install_inflight_validations) }}
      {{ "--dry-run" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_install_dry_run) }}
      {{ "--yes" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_install_yes) }}
      {{ tripleo_undercloud_install_log | tripleo.operator.shell_logging_path(combine=tripleo_undercloud_log_combine, enabled=tripleo_undercloud_log_output) }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_undercloud_install_log }}"

- name: Show the underclound install command
  debug:
    var: _install_cmd
  when: tripleo_undercloud_debug|bool

- name: undercloud install
  shell: "{{ _install_cmd }}"
  args:
    chdir: "{{ tripleo_undercloud_home_dir }}"
  async: "{{ tripleo_undercloud_install_timeout }}"
  poll: 10
