---
- name: Setup undercloud install facts
  set_fact:
    _log_location: "{{ tripleo_undercloud_home_dir }}/undercloud_install.log"
    _install_cmd: >-
      openstack undercloud install
      {{ "--force-stack-update" | shell_arg_enabled(enabled=tripleo_undercloud_install_force_stack_update) }}
      {{ "--no-validations" | shell_arg_enabled(enabled=tripleo_undercloud_install_no_validations) }}
      {{ "--inflight-validations" | shell_arg_enabled(enabled=tripleo_undercloud_install_inflight_validations) }}
      {{ "--dry-run" | shell_arg_enabled(enabled=tripleo_undercloud_install_dry_run) }}
      {{ "--yes" | shell_arg_enabled(enabled=tripleo_undercloud_install_yes) }}
      {{ _log_location | shell_logging_path(combine=tripleo_undercloud_log_combine, enabled=tripleo_undercloud_log_output) }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ _log_location }}"

- name: Running the underclound install command
  debug:
    var: _install_cmd
  when: tripleo_undercloud_debug|bool

- name: undercloud install
  shell: "{{ _install_cmd }}"
  args:
    chdir: "{{ tripleo_undercloud_home_dir }}"
