- name: Setup undercloud install facts
  set_fact:
    _tripleo_undercloud_install_log_location: "{{ tripleo_undercloud_home_dir }}/undercloud_install.log"
    _tripleo_undercloud_install: >-
      openstack undercloud install
      {{ "--force-stack-update" | shell_arg_enabled(enabled=tripleo_undercloud_install_force_stack_update) }}
      {{ "--no-validations" | shell_arg_enabled(enabled=tripleo_undercloud_install_no_validations) }}
      {{ "--inflight-validations" | shell_arg_enabled(enabled=tripleo_undercloud_install_inflight_validations) }}
      {{ "--dry-run" | shell_arg_enabled(enabled=tripleo_undercloud_install_dry_run) }}
      {{ "--yes" | shell_arg_enabled(enabled=tripleo_undercloud_install_yes) }}
      {{ _tripleo_undercloud_install_log_location | shell_logging_path(combine=tripleo_undercloud_log_combine, enabled=tripleo_undercloud_log_output) }}

- name: Running the underclound install command
  debug:
    var: _tripleo_undercloud_install
  when: tripleo_undercloud_debug|bool

- name: undercloud install
  shell: "{{ _tripleo_undercloud_install }}"
  args:
    chdir: "{{ tripleo_undercloud_home_dir }}"
