---
- name: Setup undercloud upgrade facts
  set_fact:
    _upgrade_cmd: >-
      openstack undercloud upgrade
      {{ "--force-stack-update" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_upgrade_force_stack_update) }}
      {{ "--no-validations" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_upgrade_no_validations) }}
      {{ "--inflight-validations" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_upgrade_inflight_validations) }}
      {{ "--dry-run" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_upgrade_dry_run) }}
      {{ "--yes" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_upgrade_yes) }}
      {{ tripleo_undercloud_upgrade_log | tripleo.operator.shell_logging_path(combine=tripleo_undercloud_log_combine, enabled=tripleo_undercloud_log_output) }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_undercloud_upgrade_log }}"

- name: Show the underclound upgrade command
  debug:
    var: _upgrade_cmd
  when: tripleo_undercloud_debug|bool

- name: undercloud upgrade
  shell: "{{ _upgrade_cmd }}"
  args:
    chdir: "{{ tripleo_undercloud_home_dir }}"
  async: "{{ tripleo_undercloud_upgrade_timeout }}"
  poll: 10
