---
- name: Setup undercloud minion install facts
  set_fact:
    _install_cmd: >-
      openstack undercloud minion install
      {{ "--force-stack-update" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_minion_install_force_stack_update) }}
      {{ "--no-validations" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_minion_install_no_validations) }}
      {{ "--dry-run" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_minion_install_dry_run) }}
      {{ "--yes" | tripleo.operator.shell_arg_enabled(enabled=tripleo_undercloud_minion_install_yes) }}
      {{ openstack_undercloud_minion_install_log | tripleo.operator.shell_logging_path(combine=tripleo_undercloud_minion_log_combine, enabled=tripleo_undercloud_minion_log_output) }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ openstack_undercloud_minion_install_log }}"

- name: Show the underclound minion install command
  debug:
    var: _install_cmd
  when: tripleo_undercloud_minion_debug|bool

- name: undercloud minion install
  shell: "{{ _install_cmd }}"
  args:
    chdir: "{{ tripleo_undercloud_minion_home_dir }}"
  async: "{{ tripleo_undercloud_minion_install_timeout }}"
  poll: 10
