- name: Setup undercloud minion install facts
  set_fact:
    _tripleo_undercloud_minion_install_log_location: "{{ tripleo_undercloud_home_dir }}/undercloud_minion_install.log"
    _tripleo_undercloud_minion_install: >-
      openstack undercloud minion install
      {{ "--force-stack-update" | shell_arg_enabled(enabled=tripleo_undercloud_minion_install_force_stack_update) }}
      {{ "--no-validations" | shell_arg_enabled(enabled=tripleo_undercloud_minion_install_no_validations) }}
      {{ "--dry-run" | shell_arg_enabled(enabled=tripleo_undercloud_minion_install_dry_run) }}
      {{ "--yes" | shell_arg_enabled(enabled=tripleo_undercloud_minion_install_yes) }}
      {{ _tripleo_undercloud_minion_install_log_location | shell_logging_path(combine=tripleo_undercloud_minion_log_combine, enabled=tripleo_undercloud_minion_log_output) }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ _tripleo_undercloud_minion_install_log_location }}"

- name: Running the underclound install command
  debug:
    var: _tripleo_undercloud_minion_install
  when: tripleo_undercloud_minion_debug|bool

- name: undercloud minion install
  shell: "{{ _tripleo_undercloud_minion_install }}"
  args:
    chdir: "{{ tripleo_undercloud_minion_home_dir }}"
