---
# defaults file for tripleo-undercloud-minion
tripleo_undercloud_minion_debug: False
tripleo_undercloud_minion_home_dir: "{{ ansible_env.HOME }}"
tripleo_undercloud_minion_install_dry_run: False
tripleo_undercloud_minion_install_force_stack_update: False
tripleo_undercloud_minion_install_no_validations: False
tripleo_undercloud_minion_install_yes: False
tripleo_undercloud_minion_log_combine: True
tripleo_undercloud_minion_log_output: True
tripleo_undercloud_minion_upgrade_dry_run: False
tripleo_undercloud_minion_upgrade_force_stack_update: False
tripleo_undercloud_minion_upgrade_no_validations: False
tripleo_undercloud_minion_upgrade_yes: False

