---
# defaults file for tripleo-undercloud
tripleo_undercloud_backup_add_path: []
tripleo_undercloud_backup_exclude_path: []
tripleo_undercloud_backup_timeout: 3600
tripleo_undercloud_config_sample_path: /usr/share/python-tripleoclient/undercloud.conf.sample
tripleo_undercloud_config_use_sample: true
tripleo_undercloud_config_values: {}
tripleo_undercloud_debug: false
tripleo_undercloud_home_dir: "{{ ansible_env.HOME }}"
tripleo_undercloud_install_dry_run: false
tripleo_undercloud_install_force_stack_update: false
tripleo_undercloud_install_inflight_validations: false
tripleo_undercloud_install_no_validations: false
tripleo_undercloud_install_timeout: 3600
tripleo_undercloud_install_yes: false
tripleo_undercloud_log_combine: true
tripleo_undercloud_log_output: true
tripleo_undercloud_upgrade_dry_run: false
tripleo_undercloud_upgrade_force_stack_update: false
tripleo_undercloud_upgrade_inflight_validations: false
tripleo_undercloud_upgrade_no_validations: false
tripleo_undercloud_upgrade_timeout: 3600
tripleo_undercloud_upgrade_yes: false
tripleo_undercloud_install_log: "{{ tripleo_undercloud_home_dir }}/undercloud_install.log"
tripleo_undercloud_backup_log: "{{ tripleo_undercloud_home_dir }}/undercloud_backup.log"
tripleo_undercloud_upgrade_log: "{{ tripleo_undercloud_home_dir }}/undercloud_upgrade.log"
