# tasks file for tripleo-repos
- name: Gather distribution facts
  setup:
    gather_subset: "!all,!min,distribution,distribution_major_version"

- name: Gather the rpm package facts
  package_facts:

- name: Install tripleo-repos
  include_tasks: install
  when: (ansible_facts.distribution_major_version|int <= 7 and not 'python2-tripleo-repos' in ansible_facts.packages) or
        (ansible_facts.distribution_major_version|int <= 8 and not 'python3-tripleo-repos' in ansible_facts.packages)

- name: Run tripleo-repos
  command: >-
    tripleo-repos
    -b {{ tripleo_repos_branch }}
    {{ tripleo_repos_extra_args | join(' ') }}
    {{ tripleo_repos_version }}
    {{ tripleo_repos_extra_repos | join(' ') }}
  become: true
